=== fpxtec/daw-4-uf1/app/src/test/resources/pedidos.dtd
<!ELEMENT pedidos (pedido)*>
<!ELEMENT pedido (cod_pedido, sucursal, direccion, nombre_trabajador, fecha_pedido, codigo_articulo, unidades, precio_unidad)>
<!ELEMENT cod_pedido (#PCDATA)>
<!ELEMENT sucursal (#PCDATA)>
<!ELEMENT direccion (#PCDATA)>
<!ELEMENT nombre_trabajador (#PCDATA)>
<!ELEMENT fecha_pedido (#PCDATA)>
<!ELEMENT codigo_articulo (#PCDATA)>
<!ELEMENT unidades (#PCDATA)>
<!ELEMENT precio_unidad (#PCDATA)>

=== fpxtec/daw-4-uf1/pedidos.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  Autor: Laia Romeo
-->
<!DOCTYPE pedidos SYSTEM "pedidos.dtd">
<pedidos>
        <pedido>
                <cod_pedido>1002</cod_pedido>
                <sucursal>Barcelona</sucursal>
                <direccion>C/ Caspe num 5</direccion>
                <nombre_trabajador>Juan Lopez</nombre_trabajador>
                <fecha_pedido>12/09/2019</fecha_pedido>
                <codigo_articulo>93</codigo_articulo>
                <unidades>6</unidades>
                <precio_unidad>12</precio_unidad>
        </pedido>
        <pedido>
                <cod_pedido>1003</cod_pedido>
                <sucursal>Barcelona</sucursal>
                <direccion>C/ Caspe num 5</direccion>
                <nombre_trabajador>Anna Rodiguez</nombre_trabajador>
                <fecha_pedido>20/09/2019</fecha_pedido>
                <codigo_articulo>95</codigo_articulo>
                <unidades>1</unidades>
                <precio_unidad>102</precio_unidad>
        </pedido>
        <pedido>
                <cod_pedido>1004</cod_pedido>
                <sucursal>Pamplona</sucursal>
                <direccion>C/gran v√≠a 23</direccion>
                <nombre_trabajador>Luis Perez</nombre_trabajador>
                <fecha_pedido>21/09/2019</fecha_pedido>
                <codigo_articulo>94</codigo_articulo>
                <unidades>12</unidades>
                <precio_unidad>14</precio_unidad>
        </pedido>
        <pedido>
                <cod_pedido>1005</cod_pedido>
                <sucursal>Madrid</sucursal>
                <direccion>C/Castellana 234</direccion>
                <nombre_trabajador>REbeca Mendez</nombre_trabajador>
                <fecha_pedido>22/09/2019</fecha_pedido>
                <codigo_articulo>94</codigo_articulo>
                <unidades>7</unidades>
                <precio_unidad>14</precio_unidad>
        </pedido>
</pedidos>
